// CAS-960: the on-demand accessibility scan the ticket asks for — axe-core over the five highest-traffic
// surfaces (onboarding, Watch, Agents, Moving, the film card) at 390x844 (this suite's "ios" project is
// already that viewport, CAS-162/200), plus the role/state, Dynamic Type and reduced-motion checks the
// ticket's own acceptance criteria name. NOT part of `qa` — run on demand with `npm run test:a11y`, same
// shape as `test:agents` (CAS-794). Explicitly asked for by the ticket text, so this is the one exception
// CC_AUTONOMY's "don't write a Playwright spec for your ticket" rule itself carves out.
import { test, expect } from "@playwright/test";
import AxeBuilder from "@axe-core/playwright";
import { appendFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { freshApp, toShortlist, finishFlow, toListing, openAgentsScreenFromNav } from "./helpers.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const REPORT_PATH = path.join(__dirname, "..", "..", "qa-a11y-report.txt");

const SERIOUS = new Set(["serious", "critical"]);

// File-level hook (outside every describe) so it runs exactly once before anything else in this spec,
// same clear-then-append shape as run-agent-suite.mjs's own qa-agents-report.txt handling.
test.beforeAll(() => {
  writeFileSync(REPORT_PATH,
    "CAS-960 accessibility report — axe scan, button names, contrast. Regenerated by `npm run test:a11y`.\n");
});

async function scanSurface(page, name, includeSelector) {
  let builder = new AxeBuilder({ page });
  if (includeSelector) builder = builder.include(includeSelector);
  const results = await builder.analyze();
  const serious = results.violations.filter(v => SERIOUS.has(v.impact));
  const lines = [`\n=== axe scan: ${name} ===`,
    `${results.violations.length} total violation(s), ${serious.length} serious/critical`];
  for (const v of results.violations) {
    lines.push(`  [${v.impact}] ${v.id}: ${v.help} (${v.nodes.length} node(s))`);
    for (const n of v.nodes.slice(0, 5)) lines.push(`    - ${n.target.join(" ")}`);
  }
  appendFileSync(REPORT_PATH, lines.join("\n") + "\n");
  return { all: results.violations, serious };
}

async function reachListing(page) {
  await toShortlist(page, "cinema");
  await finishFlow(page);
  await toListing(page);
}

test.describe("CAS-960 axe scan — zero serious/critical on the five named surfaces", () => {
  test("onboarding — splash", async ({ page }) => {
    await freshApp(page);
    await expect(page.locator("#splashCta")).toBeVisible();
    const { serious } = await scanSurface(page, "onboarding — splash");
    expect(serious.map(v => v.id)).toEqual([]);
  });

  test("onboarding — first step", async ({ page }) => {
    await freshApp(page);
    await page.locator("#splashCta").click();
    await expect(page.locator(".obhd")).toContainText("Let's get you set up.");
    const { serious } = await scanSurface(page, "onboarding — v2_about step");
    expect(serious.map(v => v.id)).toEqual([]);
  });

  test("Watch listing", async ({ page }) => {
    await reachListing(page);
    const { serious } = await scanSurface(page, "Watch listing");
    expect(serious.map(v => v.id)).toEqual([]);
  });

  test("the film card, expanded", async ({ page }) => {
    await reachListing(page);
    const card = page.locator("#groups .card").first();
    await expect(card).toBeVisible();
    await card.locator(".title").click();
    await expect(card).toHaveClass(/expanded/);
    const { serious } = await scanSurface(page, "the film card (expanded)");
    expect(serious.map(v => v.id)).toEqual([]);
  });

  test("Agents", async ({ page }) => {
    await reachListing(page);
    await openAgentsScreenFromNav(page);
    await expect(page.locator("#agentsScreen")).toHaveClass(/open/);
    // Scoped to #agentsScreen: it's a full-screen overlay (display:flex) sitting on top of the Watch
    // listing, which stays in the DOM underneath (covered, not display:none) — an unscoped scan would
    // also pick up Watch's own nodes and double-report anything already caught by the Watch listing test.
    const { serious } = await scanSurface(page, "Agents", "#agentsScreen");
    expect(serious.map(v => v.id)).toEqual([]);
  });

  test("Moving", async ({ page }) => {
    await reachListing(page);
    await page.locator("#movingBtn").click();
    await expect(page.locator("#movingScreen")).toHaveClass(/open/);
    const { serious } = await scanSurface(page, "Moving", "#movingScreen");
    expect(serious.map(v => v.id)).toEqual([]);
  });
});

// CAS-960 AC: "every element with role=radio, role=switch or class chip that can be selected also carries
// the matching aria-checked or aria-pressed, and the value changes when it is toggled" — a concrete
// round-trip on two real controls from the Watch mood sheet (a role=switch div and an aria-pressed
// chip button), not a blind DOM-wide click sweep (this app has disabled/decorative chips too — see
// renderMoodSheetBody's alsoShowHTML "always" chip — that a generic sweep would misfire on).
test("switches and pressed chips announce and update their state (CAS-960 AC4)", async ({ page }) => {
  await reachListing(page);
  // CAS-1247: the Filters button/badge are gone — the selected mood's own chip opens the sheet now.
  await page.locator(".moodchip.on").click();
  await expect(page.locator("#watchSheet")).toHaveClass(/open/);

  const sw = page.locator("#watchMineOnlySwitch");
  await expect(sw).toHaveAttribute("role", "switch");
  const swBefore = await sw.getAttribute("aria-checked");
  expect(["true", "false"]).toContain(swBefore);
  await sw.click();
  await expect(sw).toHaveAttribute("aria-checked", swBefore === "true" ? "false" : "true");

  const chip = page.locator("#watchSheetBody .chip:not([disabled])").first();
  const chipBefore = await chip.getAttribute("aria-pressed");
  expect(["true", "false"]).toContain(chipBefore);
  await chip.click();
  await expect(chip).toHaveAttribute("aria-pressed", chipBefore === "true" ? "false" : "true");
});

// CAS-960 AC: "grep of app_template.html finds no <button without either an aria-label or non-whitespace
// text content" — the actual assertion lives in tests/lint/a11y-buttons.mjs (no browser needed for a
// static-source check); this just proves it plugged into the same on-demand suite.
test("every button has an accessible name (CAS-960, see tests/lint/a11y-buttons.mjs)", async () => {
  const { execFileSync } = await import("node:child_process");
  expect(() => execFileSync(process.execPath, [path.join(__dirname, "..", "lint", "a11y-buttons.mjs")],
    { cwd: path.join(__dirname, "..", ".."), stdio: "pipe" })).not.toThrow();
});

// CAS-960 AC: contrast — delegates to tests/lint/a11y-contrast.mjs the same way, for the same reason.
test("text tokens clear WCAG AA contrast (CAS-960, see tests/lint/a11y-contrast.mjs)", async () => {
  const { execFileSync } = await import("node:child_process");
  expect(() => execFileSync(process.execPath, [path.join(__dirname, "..", "lint", "a11y-contrast.mjs")],
    { cwd: path.join(__dirname, "..", ".."), stdio: "pipe" })).not.toThrow();
});

// CAS-960 AC: "At the largest iOS accessibility text size emulated in Playwright, no element on those five
// surfaces has scrollWidth > clientWidth + 1 for text content, and the primary CTA on each remains within
// the viewport." The app carries no rem/em anywhere — every one of its ~98 font-size rules is a fixed px
// (see the --ui-scale comment above :root in app_template.html) — so real iOS Dynamic Type, which only
// scales relative units and system (-apple-system-body) text, would move nothing here at all. --ui-scale
// is the app's own "make everything bigger" lever (CAS-157) and the only thing that actually stands in for
// Dynamic Type's effect at the largest accessibility category, so that is what this pushes.
const DYNAMIC_TYPE_SCALE = "1.6";

async function bumpUiScale(page) {
  await page.evaluate(scale => document.documentElement.style.setProperty("--ui-scale", scale), DYNAMIC_TYPE_SCALE);
}

async function assertNoOverflow(page, surfaceName) {
  const overflowing = await page.evaluate(() => {
    const bad = [];
    document.querySelectorAll("body *").forEach(el => {
      if (el.offsetParent === null && el !== document.body) return;   // not rendered
      const style = getComputedStyle(el);
      if (style.visibility === "hidden" || style.display === "none") return;
      if (el.scrollWidth > el.clientWidth + 1 && el.textContent && el.textContent.trim()) {
        bad.push(el.className || el.tagName);
      }
    });
    return bad.slice(0, 10);
  });
  expect(overflowing, `${surfaceName}: elements with scrollWidth > clientWidth+1 — ${overflowing.join(", ")}`).toEqual([]);
}

test("Dynamic Type: onboarding does not clip and the CTA stays reachable (CAS-960 AC6)", async ({ page }) => {
  await freshApp(page);
  await bumpUiScale(page);
  await expect(page.locator("#splashCta")).toBeVisible();
  await expect(page.locator("#splashCta")).toBeInViewport();
  await assertNoOverflow(page, "onboarding — splash");

  await page.locator("#splashCta").click();
  await expect(page.locator(".obhd")).toContainText("Let's get you set up.");
  await expect(page.locator("#onbStepCta:visible, #flowCta:visible").first()).toBeInViewport();
  await assertNoOverflow(page, "onboarding — v2_about step");
});

test("Dynamic Type: Watch, the film card, Agents and Moving do not clip (CAS-960 AC6)", async ({ page }) => {
  await reachListing(page);
  await bumpUiScale(page);
  await assertNoOverflow(page, "Watch listing");

  const card = page.locator("#groups .card").first();
  await card.locator(".title").click();
  await expect(card).toHaveClass(/expanded/);
  await assertNoOverflow(page, "the film card (expanded)");

  await openAgentsScreenFromNav(page);
  await expect(page.locator("#agentsScreen")).toHaveClass(/open/);
  await expect(page.locator(".ag-add")).toBeInViewport();
  await assertNoOverflow(page, "Agents");

  // openMovingScreen() closes Agents itself (see its own closeAgentsScreen() call) — opening Agents again
  // has no toggle-off click of its own, it always (re-)opens.
  await page.locator("#movingBtn").click();
  await expect(page.locator("#movingScreen")).toHaveClass(/open/);
  await assertNoOverflow(page, "Moving");
});

// CAS-960 AC: "With prefers-reduced-motion: reduce, no element on those surfaces reports a non-none
// animationName." emulateMedia's reduced-motion covers the whole browsing context, same as a real device
// setting — no per-element opt-in needed on this app's side beyond the @media queries it already ships.
test.describe("reduced motion (CAS-960 AC7)", () => {
  test.use({ reducedMotion: "reduce" });

  async function assertNoAnimation(page, surfaceName) {
    const animating = await page.evaluate(() => {
      const bad = [];
      document.querySelectorAll("body *").forEach(el => {
        // Only elements actually on screen — the app keeps every other .uscreen (Account, Languages, the
        // rest of the menu) in the DOM at display:none, and this check must be about the open surface,
        // not every screen the app happens to carry.
        if (el.offsetParent === null && el !== document.body) return;
        const style = getComputedStyle(el);
        if (style.visibility === "hidden" || style.display === "none") return;
        const name = style.animationName;
        if (name && name !== "none") bad.push(`${el.className || el.tagName}:${name}`);
      });
      return bad.slice(0, 10);
    });
    expect(animating, `${surfaceName}: animated elements — ${animating.join(", ")}`).toEqual([]);
  }

  test("onboarding honours reduced motion", async ({ page }) => {
    await freshApp(page);
    await expect(page.locator("#splashCta")).toBeVisible();
    await assertNoAnimation(page, "onboarding — splash");
    await page.locator("#splashCta").click();
    await expect(page.locator(".obhd")).toContainText("Let's get you set up.");
    await assertNoAnimation(page, "onboarding — v2_about step");
  });

  test("Watch, the film card, Agents and Moving honour reduced motion", async ({ page }) => {
    await reachListing(page);
    await assertNoAnimation(page, "Watch listing");

    const card = page.locator("#groups .card").first();
    await card.locator(".title").click();
    await expect(card).toHaveClass(/expanded/);
    await assertNoAnimation(page, "the film card (expanded)");

    await openAgentsScreenFromNav(page);
    await expect(page.locator("#agentsScreen")).toHaveClass(/open/);
    await assertNoAnimation(page, "Agents");

    await page.locator("#movingBtn").click();
    await expect(page.locator("#movingScreen")).toHaveClass(/open/);
    await assertNoAnimation(page, "Moving");
  });
});
